
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Oct 21 15:14:01 GMT-05:00 2002
//----------------------------------------------------

package command.parser;

/** CUP generated class containing symbol constants. */
public class TT {
  /* terminals */
  public static final int SEQ = 53;
  public static final int ABS = 32;
  public static final int SLASH = 36;
  public static final int UN_OP = 65;
  public static final int ACSC = 14;
  public static final int FULL_ROW_REDUCE = 64;
  public static final int UNDEFINE = 47;
  public static final int SEC = 9;
  public static final int LPAREN = 44;
  public static final int SEMI = 42;
  public static final int COTH = 22;
  public static final int FCONST = 3;
  public static final int DISPLAY_FRACTIONS = 62;
  public static final int TAN = 7;
  public static final int MINUS = 35;
  public static final int ACOT = 16;
  public static final int STAR = 37;
  public static final int ACOS = 12;
  public static final int CSCH = 20;
  public static final int RPAREN = 45;
  public static final int DEFINE = 46;
  public static final int EVAL = 48;
  public static final int COMMA = 41;
  public static final int LN = 31;
  public static final int LOCK = 56;
  public static final int ACOTH = 28;
  public static final int SINH = 17;
  public static final int ASIN = 11;
  public static final int PLUS = 34;
  public static final int CARET = 38;
  public static final int CSC = 8;
  public static final int SECH = 21;
  public static final int EXCL = 43;
  public static final int ACSCH = 26;
  public static final int EOF = 0;
  public static final int COSH = 18;
  public static final int TRUE = 60;
  public static final int error = 1;
  public static final int COT = 10;
  public static final int INTEGRATE = 33;
  public static final int COS = 6;
  public static final int MOD = 29;
  public static final int IDENT = 2;
  public static final int ASINH = 23;
  public static final int EQ = 39;
  public static final int LBRACK = 51;
  public static final int ASECH = 27;
  public static final int LOG = 30;
  public static final int ARROW = 40;
  public static final int LBRACE = 49;
  public static final int ACOSH = 24;
  public static final int RBRACK = 52;
  public static final int TANH = 19;
  public static final int SIN = 5;
  public static final int UNFREEZE = 59;
  public static final int ICONST = 4;
  public static final int RBRACE = 50;
  public static final int SUM = 54;
  public static final int PROD = 55;
  public static final int ASEC = 15;
  public static final int FREEZE = 58;
  public static final int FALSE = 61;
  public static final int UNLOCK = 57;
  public static final int ATAN = 13;
  public static final int ATANH = 25;
  public static final int SET = 63;
}

